### ISSUE TITLE
Debug message is filling the log

### ISSUE THREAD

**Issue by fikrimi23** [timecamp/timecamp-v2.1-desktop-app#39]
pretty much self explanatory, right now, my journalctl is filled with much timecamp debug message, or is this an intended behaviour?

**Comment by karololszacki** [comment]
We're still having debug log level as default, but this may change in the future versions.

For now, see this doc to configure your log level:
http://doc.qt.io/qt-5/qloggingcategory.html#configuring-categories

Basically create a `qtlogging.ini` file with specified `QT_LOGGING_RULES`

**Comment by fikrimi23** [comment]
Ok, right now I have 
`~/.config/QtProject/qtlogging.ini`
`~/.config/Timecamp SA/qtlogging.ini`
`/etc/environment`

all with single line:
`QT_LOGGING_RULES='*=false'`

and it still logging

**Comment by RX14** [comment]
`QT_LOGGING_RULES="*=false"` works as an env var.

```
$ QT_LOGGING_RULES="*=false" timecamp
[LOG PATH] /home/rx14/.local/share/TimeCamp SA/TimeCamp Desktop/logs

(timecamp:26544): Gtk-WARNING **: 00:45:53.848: Unable to locate theme engine in module_path: "adwaita",

(timecamp:26544): Gtk-WARNING **: 00:45:53.848: Unable to locate theme engine in module_path: "adwaita",
libpng warning: iCCP: known incorrect sRGB profile
^C

```

I suggest that the env var isn't actually being set.

**Comment by fikrimi23** [comment]
i rebooted and now its gone, 
i dunno which one did it (addition from those above, the other forum suggest to export QT_LOGGING_RULES var)

but for now, I am happy there's no more timecamp debug message
