### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by fikrimi23** [timecamp/timecamp-v2.1-desktop-app#65]
I get this 100% CPU usage using the AppImage version, already tried some version and the issue still persists. Currently, I am using the latest pre-release (2.1.4.3-b418)

![image](https://user-images.githubusercontent.com/8409391/55894229-f2c1c600-5be3-11e9-9de7-ba40a05b9666.png)

I also had the other version from AUR (v 2.1.1.0), and it's fine, but sometimes it will hog 40% from one of my CPU by QTWebProcess.

![image](https://user-images.githubusercontent.com/8409391/55894070-a9717680-5be3-11e9-99c5-a473d2db5805.png)

Environment :
OS: Arch Linux 4.19.34-1-lts, all up to date (per 10 April 2019)
Desktop: GNOME 3.32

I'll be glad if to give more information

**Comment by karololszacki** [comment]
Hi, can you see if you have any logs from the app? The path to logs is displayed on your second screenshot.

As far as I know, we didn't upload this app to any repository yet, so whatever is in AUR - probably can't be trusted, unless it's directly compiled from sources (I don't know how AUR operates).
Is this the one? https://aur.archlinux.org/packages/timecamp/

I have an idea of what might be causing high CPU usage of our binary (so, the 1st case) - but anything that happens in QtWebProcesses is probably out of our scope (unless we invoke something, but then we'd have high usage on our side too).

**Comment by fikrimi23** [comment]
for the AUR version, yes I know its community maintained but according to the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=timecamp)

It downloads from the Github repository, currently, its version 2.1.1 (flagged out of date ofc). Then checks the sum and then try to build (with cmake nad make) and then just copy it to bin
```
...
pkgver=2.1.1.0
...
source=("timecamp-${pkgver}.tar.gz::https://github.com/timecamp/timecamp-v2.1-desktop-app/archive/${pkgver}.tar.gz"
        "timecamp.desktop")
sha256sums=('1ed3904dc3b99f4a84a637dbeb8d5d130e0d31859fdf7ce34229b374b24183c8'
            '632c47beefd1aae80eb3ea51832fd74e43f11ed6432f5dc7dded867c80d5df70')

build() {
  ...

  cmake ..
  make
}


package() {
  cd "$srcdir/timecamp-v2.1-desktop-app-${pkgver}"
  install -D -m755 build/TimeCampDesktop "$pkgdir/usr/bin/timecamp" 
  ...
}
```
the [desktop file](https://aur.archlinux.org/cgit/aur.git/tree/timecamp.desktop?h=timecamp) just `Exec=/usr/bin/timecamp`

and for the appimage version

![image](https://user-images.githubusercontent.com/8409391/55941903-652ab880-5c6d-11e9-9a3a-3b0363c24a6a.png)

Unfortunately
- the log just contains nothing, I don't know if it's a permission error, but trying to chmod 777 to the folder doesn't help. 
- I also try changing my kernel, currently I am on 5.0.7-zen1-1-zen and it doesnt help either. 
- Trying to disable gnome extension just make it pop up the error that I dont have tray icons, and still getting 100% cpu usage

**Comment by karololszacki** [comment]
Please try this AppImage:
https://github.com/timecamp/timecamp-v2.1-desktop-app/releases/tag/continuous-ko%2Ffix%2Fbulk-april

It's based on fixes from this branch: https://github.com/timecamp/timecamp-v2.1-desktop-app/pull/64

Please also try clearing the whole data directory (`~/.local/share/TimeCamp SA/TimeCamp Desktop`).

**Comment by karololszacki** [comment]
I will have to read up about the `PKGBUILD` format, and maybe when we'll have some available time we will create our own, but after a first glance it looks ok.

In the future we will look into The Open Build Service (OBS), but this is a lower priority.

Our focus will be towards a custom Qt-based GUI and dropping the WebEngine dependency, and then maybe static builds (which WebEngine blocks). We want that to avoid the "dependency hell", as we want to provide this app for eg. old Ubuntus as well, but their Qt5 is old, so we provide the AppImage with bundled Qt... Lots of issues with all of this, and a huge amount of work.

**Comment by fikrimi23** [comment]
Thank you very much, it fixes the 100% cpu problem.

However, the QTWebEngineProcess is still (maybe) using an unusual amount of CPU, yet not really as bad as the v2.1.1.0 version from aur, I can live with this. Much appreciated

![image](https://user-images.githubusercontent.com/8409391/55943614-17b04a80-5c71-11e9-9704-9649c80083f6.png)

Just a little bit of my opinion, I think the apps should only just track, when click show, it should be redirected to the webpage version. Somehow I feel redundant to have it in "show", yet the inside is just the web version (that I more comfortable access via browser)

**Comment by karololszacki** [comment]
There is the app from the 1.x line which only does activities tracking and task switching.
You can get it from the website, or at [this link](https://new.timecamp.com/downloadsoft/1.4.5.3/TimeCampSetup_LinAmd64.tar.gz).

Most of our users wanted to do more than just tracking and task switching from the app, that's why our shortcut was to embed a browser in the app. In the future we will have our own Qt-based GUI for the most requested interfaces.

**Comment by fikrimi23** [comment]
nah really, it's just us, the Arch community that doesn't want to wait the official release of the app to the platform (the Arch official repository), so they try to make a list of instruction (PKGBUILD) to download (usually) from github repository and try to compile it themselves, we as a user will only need the pkgbuild, because all the process is automated. Sometimes it will just pull from .deb package or .tar.gz from official website.

**Comment by fikrimi23** [comment]
of PKGBUILD 

> There is the app from the 1.x line which only does activities tracking and task switching.
> You can get it from the website, or at [this link](https://new.timecamp.com/downloadsoft/1.4.5.3/TimeCampSetup_LinAmd64.tar.gz).
> 
> Most of our users wanted to do more than just tracking and task switching from the app, that's why our shortcut was to embed a browser in the app. In the future we will have our own Qt-based GUI for the most requested interfaces.

Oo, ok then. I will stick with the latest version. Keep up the good work, I love the apps.
